workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.qssun.reports"
        APP_NAME: "Qssun Reports Beta"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      
      - name: Build web assets
        script: |
          npm run build
          npx cap sync ios
      
      - name: Setup iOS certificates
        script: |
          # This will use the certificates you upload to Codemagic
          echo "iOS certificates will be configured from environment variables"
      
      - name: Build iOS Archive
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' -archivePath build/App.xcarchive archive CODE_SIGNING_ALLOWED="no" CODE_SIGNING_REQUIRED="no"
      
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist CODE_SIGNING_ALLOWED="no"
        ignore_failure: true
    artifacts:
      - ios/App/build/App.xcarchive/**/
      - ios/App/build/*.ipa
      - ios/App/build/*.xcarchive
    publishing:
      email:
        recipients:
          - your-email@example.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.qssun.reports"
        APP_NAME: "Qssun Reports Beta"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      
      - name: Build web assets
        script: |
          npm run build
          npx cap sync android
      
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com