workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.qssun.reports"
        APP_NAME: "Qssun Reports Beta"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      
      - name: Build web assets
        script: |
          npm run build
          npx cap sync ios
      
      - name: Setup iOS certificates
        script: |
          # This will use the certificates you upload to Codemagic
          echo "iOS certificates will be configured from environment variables"
          # Configure code signing if certificates are available
          if [ -n "$CM_CERTIFICATE" ]; then
            keychain initialize
            app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
            keychain add-certificates
            xcode-project use-profiles
          fi
      
      - name: Build iOS Archive
        script: |
          cd ios/App
          if [ -n "$CM_CERTIFICATE" ]; then
            xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' -archivePath build/App.xcarchive archive
          else
            xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' -archivePath build/App.xcarchive archive CODE_SIGNING_ALLOWED="no" CODE_SIGNING_REQUIRED="no"
          fi
      
      - name: Export IPA
        script: |
          cd ios/App
          if [ -n "$CM_CERTIFICATE" ]; then
            xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
          else
            echo "Code signing not configured - skipping IPA export"
          fi
        ignore_failure: true
    artifacts:
      - ios/App/build/App.xcarchive/**/
      - ios/App/build/*.ipa
      - ios/App/build/*.xcarchive
    publishing:
      email:
        recipients:
          - your-email@example.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.qssun.reports"
        APP_NAME: "Qssun Reports Beta"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      
      - name: Build web assets
        script: |
          npm run build
          npx cap sync android
      
      - name: Setup Android signing
        script: |
          # Setup Android signing if keystore is available
          if [ -n "$CM_KEYSTORE" ]; then
            echo "Setting up Android signing"
            # This will use the keystore you upload to Codemagic
          else
            echo "No keystore configured - building debug version"
          fi
      
      - name: Build Android APK
        script: |
          cd android
          if [ -n "$CM_KEYSTORE" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
      
      - name: Build Android App Bundle
        script: |
          cd android
          if [ -n "$CM_KEYSTORE" ]; then
            ./gradlew bundleRelease
          else
            echo "No signing configured - skipping AAB build"
          fi
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal

  web-build:
    name: Web Build
    max_build_duration: 30
    environment:
      vars:
        APP_NAME: "Qssun Reports Beta"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build web application
        script: |
          npm run build
      
      - name: Optimize build
        script: |
          # Optimize build for production
          echo "Build completed successfully"
          ls -la dist/
    artifacts:
      - dist/**
      - build/**
      - .next/**
    publishing:
      email:
        recipients:
          - your-email@example.com
      scripts:
        - name: Deploy to Vercel
          script: |
            # Optional: Deploy to Vercel if configured
            if [ -n "$VERCEL_TOKEN" ]; then
              npm install -g vercel
              vercel --prod --token=$VERCEL_TOKEN --yes
            fi